export const LOGO_ALT_TEXT = 'logo';
export const LOG_IN_ALT_TEXT = 'log-in';
export const MENU_ALT_TEXT = 'burger-menu';
export const LABEL_EMAIL = 'Email';
export const LABEL_PASS = 'Пароль';
export const AUTH = 'Вход';
export const AUTH_BTN = 'Войти';
export const REGISTATION = 'Зарегистрироваться';
export const ERROR_AUTH_MSG = 'Неправильный логин или пароль';
