export const itemData = [
  {
    furniture: 'chair',
    imgSrc: './images/стул1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'chair',
    imgSrc: './images/стул1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'chair',
    imgSrc: './images/стул1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'chair',
    imgSrc: './images/стул1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'chair',
    imgSrc: './images/стул1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'chair',
    imgSrc: './images/стул1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'chair',
    imgSrc: './images/стул1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'chair',
    imgSrc: './images/стул1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'chair',
    imgSrc: './images/стул1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'sofa',
    imgSrc: './images/диван1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'sofa',
    imgSrc: './images/диван1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'sofa',
    imgSrc: './images/диван1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'sofa',
    imgSrc: './images/диван1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'sofa',
    imgSrc: './images/диван1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'sofa',
    imgSrc: './images/диван1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'sofa',
    imgSrc: './images/диван1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'sofa',
    imgSrc: './images/диван1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'sofa',
    imgSrc: './images/диван1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'table',
    imgSrc: './images/столЖурнальный1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'table',
    imgSrc: './images/столЖурнальный1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'table',
    imgSrc: './images/столЖурнальный1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'table',
    imgSrc: './images/столЖурнальный1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'table',
    imgSrc: './images/столЖурнальный1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'table',
    imgSrc: './images/столЖурнальный1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'table',
    imgSrc: './images/столЖурнальный1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'table',
    imgSrc: './images/столЖурнальный1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
  {
    furniture: 'table',
    imgSrc: './images/столЖурнальный1.jpg',
    imgAlt: 'стул1',
    name: 'Стул Jenny, черный',
    itemSize: 'ШxГxВ: 53x49x75',
    itemUpholstery: 'Материал обивки: Экокожа',
    itemMaterial: 'Материал ножек: Дерево',
    itemPrice: '1$',
  },
];
