export const TAGS: Record<string, string> = {
  a: 'a',
  li: 'li',
  img: 'img',
  nav: 'nav',
  ul: 'ul',
  div: 'div',
  header: 'header',
  input: 'input',
  label: 'label',
  span: 'span',
  form: 'form',
  h1: 'h1',
  button: 'button',
  main: 'main',
};
